ignore:
    ["Spaceship_Server_Rotate_Test"]
codecov:
  token: ${{ secrets.CODECOV_TOKEN }}
coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    # notification blocks. See: https://docs.codecov.io/docs/codecovyml-reference#section-coverage-notify
  status:
    project:
    patch:
    changes:
