ignore:
  ["Spaceship.Macro.Test", "Spaceship.Exceptions.Test", "Spaceship.IoC.Test.No.Strategies"]
codecov:
  token: ${{ secrets.CODECOV_TOKEN }}
fixes:
  - "Spaceship__Server/::"
  - "Isachenko-Bauer-MO-211/::"
  - "./::"
  - "main/::"
   - "::/Spaceship__Server"
  - "::/Isachenko-Bauer-MO-211/"
  - "::/"
  - "::/main" 

