name: .Net 6 CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore 

    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Setup test enviroment
      run: dotnet tool install --global dotnet-coverage
    - name: Test
      run: dotnet test  --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    #- name: Test
    #  run: dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage1.xml'
    #- name: ls
    #  run: ls
    #- name: head1
    #  run: head coverage1.xml
    #- name: head2
    #  run: head output.xml
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: Spaceship.IoC.Test.No.Strategies/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '20 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md