name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@Spaceship_Move_Test
    - name: Setup .NET
      uses: actions/setup-dotnet@Spaceship_Move_Test
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --collect "Code Coverage"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@Spaceship_Move_Test
